version: "3.4"

services:
  mongodb: 
    image: "mongo:7.0"
    container_name: "mongodb"
    command:
      - "--replSet"
      - "rs0"
      - "--bind_ip_all"
    ports:
      - 27017
      - 27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: >
        echo "if (!rs.status().ok) rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'host.docker.internal:27017'}]})" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s
      start_interval: 1s
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/config/db
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
networks:
  default:
    name: TicketingNetwork